modules/make.nu, modules/nupac.nu, modules/remoting.nu, nupac.json
=> add urls to modules

modules/nupac.nu
=> 2 config variables

DESIGN.md
=> env variables got documented

modules/nupac.nu
=> default flag values, simpler env-checks

.gitignore
=> pre-commit-config added to gitignore

.github/workflows/ci.yml
=> Disable docker caching

.github/workflows/ci.yml
=> Disable docker caching (#26)

.github/workflows/ci.yml, generate-repo-cache.nu, modules/nupac.nu, testing/molecule/default/Dockerfile.j2
Solves https://github.com/skelly37/nupac/issues/14
Basically the developers will be able to leave some pre- or post-install messages for the users
=> Pre & post install messages

README.md, docs/CODING_STANDARDS.md
My first thoughts gathered, to be reviewed, enhanced and refactored
=> initial coding standards

.github/workflows/release.yml, .gitignore, .pre-commit-config.yaml, docs/CODING_STANDARDS.md, setup-pre-commit.nu
=> pre-commit introduced

testing/molecule/default/search-descriptions.yml
=> fix assertions

.github/workflows/release.yml
=> force push on release

.github/workflows/ci.yml, docs/PACKAGE_MANIFEST.md, generate-repo-cache.nu, repo-cache.json
=> Checksums2

.github/ISSUE_TEMPLATE/question.yml
I've added it to Nushell repo today and I think it might be useful some day, so I'll just drop it there
Please mark as done everything appliable to the current state of your PR
=> Created an issue template for questions

installer.nu, modules/nupac.nu, modules/remoting.nu, repo-cache.json, testing/docker/Dockerfile, testing/linter.nu, testing/molecule/default/molecule.yml
*description of your pull request here*
Please mark as done everything appliable to the current state of your PR
*do you have some questions, need some help or anything else?*
=> For real this time

.github/workflows/ci.yml, installer.nu, modules/nupac.nu, modules/remoting.nu, repo-cache.json, testing/docker/Dockerfile, testing/linter.nu, testing/molecule/default/molecule.yml
*description of your pull request here*
Please mark as done everything appliable to the current state of your PR
*do you have some questions, need some help or anything else?*
=> Linter fixes2

modules/make/make.json, modules/nupac/nupac.json, modules/remoting/remoting.json, repo-cache.json
Patched invalid URLs in metadata from the previous PR
=> JSON URLs patched

.github/ISSUE_TEMPLATE/bug_report.yml
=> Typo fix in bug report

installer.nu
I've started with uncommenting the existing code as https://github.com/skelly37/nupac/issues/88 got solved yesterday and it works fine.
Please mark as done everything appliable to the current state of your PR
Would we like to test it anyway? ping @Yethal
=> Validate repo cache checksum in the nupac installer

.github/workflows/docker.yml, testing/docker/Dockerfile
[//]: # (*description of your pull request here*)
[//]: # (*Please mark as done everything appliable to the current state of your PR*)
[//]: # (*do you have some questions, need some help or anything else?*)
=> Fixed docker after migration to a project

.github/workflows/docker.yml
[//]: # (*description of your pull request here*)
[//]: # (*Please mark as done everything appliable to the current state of your PR*)
[//]: # (*do you have some questions, need some help or anything else?*)
=> Fix docker cleanup
